### ISSUE TITLE
Have a panel (or tab) to control clustering models

### ISSUE THREAD

**Issue by regel** [regel/chronograf#16]
Loud ML EE has clustering support. The API to control creation, training, delete, start, stop, etc is the same, and accepts the same parameters. However, the model settings will differ at model creation time.

A panel, or tab, to configure new clustering model can be added and reuse the code that already exists.

- [x] No man is an island blog article. Read on, for more info.
- [x] UX proposal: panel, or tab, second list or not, etc.
- [ ] Documentation and examples
- [x] Dataset, and sandbox, to test the API
- [ ] Have a new cell type, highly specific to clustering infos.

1click ML: Nothing changes.

**Comment by sbettevy** [comment]
It's `fingerprints` model type.
`span` setting already exists in the Parameters panel.

So only `key` is needed in the configure model view. I'm wrong?

**Comment by regel** [comment]
Key, and width, height to set the size of the clustering map.

**Comment by sbettevy** [comment]
First move model name input from General panel to ModelPage header. This value exists in both header and General panel when edit after creation (duplicate info)

![capture d ecran 2018-10-24 a 10 18 00](https://user-images.githubusercontent.com/16062976/47416498-231cc180-d776-11e8-8626-022fa5a15e6d.png)

![capture d ecran 2018-10-24 a 10 21 23](https://user-images.githubusercontent.com/16062976/47416738-a1796380-d776-11e8-9576-48c0e8ffc705.png)

**Comment by regel** [comment]
ok

**Comment by sbettevy** [comment]
Add new component in General panel to select 'timeseries' or 'fingerprints' model type
![capture d ecran 2018-10-24 a 13 05 07](https://user-images.githubusercontent.com/16062976/47426453-85cd8780-d78d-11e8-85b1-e5cefdd06a4a.png)

**Comment by sbettevy** [comment]
Add 'Clustering' panel to handle `key`, `width` and `height` values.
Q: is key selectable from a dropdown list? from which data (eg measurement)?

**Comment by sbettevy** [comment]
select `timeseries` should:
- disable Clustering panel
- show `io` parameters in Feature panel
- hide low and high watermark parameters in Feature panel

select `fingerprints` should:
- enable Clustering panel
- hide `io` parameters in Features panel (not relevant)
- show low and high watermark parameters in Feature panel

We've added `low_watermark` (float, or null) and `high_watermark` (float, or null) in feature properties in order to ensure certain features will stay above a minimum, or below a maximum value at all times.

Key: it's a tag name. If there is a dropdown selection, it can be any tag that's available.

Clustering panel: we can we use the Parameters tab directly, right? It will be locked once the model is trained, as expected.

select `timeseries` should:
- show `span`,`forecast`,`seasonality`  parameters in Parameters panel
- hide `key`,`width`,`height`  parameters in Parameters panel

select `fingerprints` should:
- hide `span`,`forecast`,`seasonality`  parameters in Parameters panel
- show `key`,`width`,`height`  parameters in Parameters panel

**Comment by regel** [comment]
edited previous comment, @sbettevy what do you think?

**Comment by sbettevy** [comment]
Ok to reuse Parameters panel slot. In fact two real panels will be fine to test (= same slot/name, two components).
Assert `key` is a tag name. So linked to measurement? How to handle different measurements from features? Should we make a model syntax review?

**Comment by sbettevy** [comment]
Fingerprints panel
TODO: change key to combobox component
 - dropdown with tags list
 - input field for custom value
![capture d ecran 2018-11-11 a 11 04 51](https://user-images.githubusercontent.com/16062976/48311574-f8b66b00-e5a1-11e8-8681-780403e74a36.png)

**Comment by regel** [comment]
@sbettevy : dropdown + custom text input would a good option eg. similar to the default value selection (previous/none/null/number) widget
