### ISSUE TITLE
DB.retentionPolicy and the impact on 1click ML action

### ISSUE THREAD

**Issue by regel** [regel/chronograf#20]
v1.6.1

Retention policy 'autogen' is the default, but others can be defined too. This information is selected in the Data Explorer, and should be given to Loud ML with the 1click ML action.

Loud ML will select database, and retention policy, in order to query the data.

First things first: we have to understand the impact with the current implementation.

**Comment by sbettevy** [comment]
1-Click ML get DB `database` and RP `retentionPolicy` from the redux store and get up to date values from user actions in the Dataexplorer view.
When change occurs new Loud ML datasource value is fetched from `/datasources` API. Finding datasource is based on Loud ML `database` and Chronograf `database` (=).

RP is forced to `autogen` for _dashboard actions_ because it does not exist on datasource object.

adding retentionPolicy to the database value `database: "DB.RP"` is an option for right choose the datasource to create model (1-Click) and have correct values to create dashboards (cell queries based on DB and RP).

**Impacts**
OneClick._getDatasource(): Finding datasource is based on Loud ML `database` and Chronograf `database.retentionPolicy` (=)
OneClick.componentDidUpdate(): Fetch Loud ML datasources based on props `database` AND `retentionPolicy`
createErrorQueryConfig/createModelQueryConfig (query.js): `{database, retentionPolicy}`
QUERY_CONFIG (query.js): `retentionPolicy: DEFAULT_LOUDML_RP`

Why not change term? 
InfluxDB => Databases and Retention Policies => Measurements => Fields and Tags
MySQL => Databases => Tables => Columns/Rows
Elasticsearch => Indices => Types => Documents with Properties
...

**Comment by sbettevy** [comment]
new `autogen` key on Loud ML 1.4.3

**Comment by sbettevy** [comment]
retention policy set to "autogen" if not exists in datasource definition
